// <auto-generated />
using Company_System.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day1Company_System.DAL.Migrations
{
    [DbContext(typeof(Company_SystemContext))]
    [Migration("20240928132524_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("Company_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            DepartmentId = 1,
                            ImgUrl = "1.png",
                            Name = "ahmed",
                            Salary = 5000.0
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            DepartmentId = 2,
                            ImgUrl = "2.png",
                            Name = "ayman",
                            Salary = 10000.0
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            DepartmentId = 3,
                            ImgUrl = "3.png",
                            Name = "yasser",
                            Salary = 8000.0
                        },
                        new
                        {
                            Id = 4,
                            Age = 29,
                            DepartmentId = 4,
                            ImgUrl = "1.png",
                            Name = "yara",
                            Salary = 7000.0
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            DepartmentId = 1,
                            ImgUrl = "2.png",
                            Name = "tamer",
                            Salary = 6000.0
                        });
                });

            modelBuilder.Entity("Company_System.Models.Employee", b =>
                {
                    b.HasOne("Company_System.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Company_System.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
